// <auto-generated />
using System;
using System.Text.Json;
using AiModelEvalCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiModelEvalCenter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Framework")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("AiModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mock Object Detection Model",
                            Framework = "ONNX",
                            IsActive = true,
                            ModelType = "object_detection",
                            Name = "YOLOv8-Aerial",
                            Version = "2.3.1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "High precision tactical model",
                            Framework = "TensorRT",
                            IsActive = true,
                            ModelType = "object_detection",
                            Name = "RT-DETR-Tactical",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Thermal segmentation model",
                            Framework = "PyTorch",
                            IsActive = true,
                            ModelType = "segmentation",
                            Name = "Thermal-Seg",
                            Version = "4.0"
                        });
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.DriftMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ClassificationCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfidenceDelta")
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid>("GroundTruthId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InferenceId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("IouScore")
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("GroundTruthId");

                    b.HasIndex("InferenceId")
                        .IsUnique();

                    b.ToTable("DriftMetrics");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.GroundTruth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrueClass")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("FrameId")
                        .IsUnique();

                    b.ToTable("GroundTruths");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.ModelInference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedClass")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("InferenceLatencyMs")
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("RawOutput")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.HasIndex("ModelId", "CreatedAt");

                    b.ToTable("ModelInferences");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.TelemetryFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AltitudeM")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FrameSequence")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HeadingDeg")
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("SensorPayloadUri")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("VelocityMps")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CapturedAt");

                    b.HasIndex("SessionId", "FrameSequence")
                        .IsUnique();

                    b.ToTable("TelemetryFrames");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.TelemetrySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("TelemetrySessions");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.DriftMetric", b =>
                {
                    b.HasOne("AiModelEvalCenter.Domain.Entities.GroundTruth", "GroundTruth")
                        .WithMany()
                        .HasForeignKey("GroundTruthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiModelEvalCenter.Domain.Entities.ModelInference", "Inference")
                        .WithOne()
                        .HasForeignKey("AiModelEvalCenter.Domain.Entities.DriftMetric", "InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroundTruth");

                    b.Navigation("Inference");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.GroundTruth", b =>
                {
                    b.HasOne("AiModelEvalCenter.Domain.Entities.TelemetryFrame", "Frame")
                        .WithOne()
                        .HasForeignKey("AiModelEvalCenter.Domain.Entities.GroundTruth", "FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AiModelEvalCenter.Domain.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("GroundTruthId");

                            b1.Property<double>("H");

                            b1.Property<double>("W");

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.HasKey("GroundTruthId");

                            b1.ToTable("GroundTruths");

                            b1
                                .ToJson("BoundingBox")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GroundTruthId");
                        });

                    b.Navigation("BoundingBox");

                    b.Navigation("Frame");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.ModelInference", b =>
                {
                    b.HasOne("AiModelEvalCenter.Domain.Entities.TelemetryFrame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AiModelEvalCenter.Domain.Entities.AiModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AiModelEvalCenter.Domain.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("ModelInferenceId");

                            b1.Property<double>("H");

                            b1.Property<double>("W");

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.HasKey("ModelInferenceId");

                            b1.ToTable("ModelInferences");

                            b1
                                .ToJson("BoundingBox")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ModelInferenceId");
                        });

                    b.Navigation("BoundingBox");

                    b.Navigation("Frame");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AiModelEvalCenter.Domain.Entities.TelemetryFrame", b =>
                {
                    b.HasOne("AiModelEvalCenter.Domain.Entities.TelemetrySession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
